name: Run AQAvit

on:
  workflow_dispatch: # Allows the job to be manually triggered
    inputs:
      pool:
        descrption: pool
        required: true

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: true
  CUSTOMIZED_SDK_URL: https://aka.ms/download-jdk/microsoft-jdk-11.0.18-linux-x64.tar.gz

jobs:
  configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Select agent
        id: agent-configurtation
        run: |
          if [[ ${{ inputs.pool }} == "*macos-x64*" ]]; then
            echo "config=[macos-10.15]" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.pool }} == "*macos-arm64*" ]]; then
            echo "config=['self-hosted', 'MacOS', 'ARM64']" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.pool }} == "*windows2019-x64*" ]]; then
            echo "config=['self-hosted', 'windows', 'x64']" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.pool }} == "*windows2022-aarch64*" ]]; then
            echo "config=['self-hosted', 'windows', 'ARM64']" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.pool }} == "*ubuntu20.04-x64*" ]]; then
            echo "config=['self-hosted', 'linux', 'x64']" >> $GITHUB_OUTPUT
          fi
          if [[ ${{ inputs.pool }} == "*ubuntu20.04-aarch64*" ]]; then
            echo "config=['self-hosted', 'linux', 'ARM64']" >> $GITHUB_OUTPUT
          fi

    outputs:
      agent-configuration: ${{ steps.agent-configuration.outputs.config }}

  run_aqa:
    runs-on: ${{ fromJSON(needs.configuration.outputs.agent-configuration) }}
    needs: configuration
    strategy:
      fail-fast: false
      matrix:
        target: [sanity, extended]
        suite: [functional, openjdk, system, perf]
        include:
          - target: special
            suite: functional

    steps:

    - name: Run AQA Tests - ${{ matrix.target }}.${{ matrix.suite }}
      uses: adoptium/run-aqa@v2.0.1
      with:
        jdksource: 'customized'
        customizedSdkUrl: ${{ env.CUSTOMIZED_SDK_URL }}
        aqa-testsRepo: 'adoptium/aqa-tests:v0.9.6-release' # Make sure this branch is set to the latest release branch
        build_list: ${{ matrix.suite }}
        target: _${{ matrix.target }}.${{ matrix.suite }}

    - uses: actions/upload-artifact@v2
      if: always() # Always run this step (even if the tests failed)
      with:
        name: test_output
        path: ./**/output_*/*.tap