name: Run AQAvit

on:
  workflow_dispatch: # Allows the job to be manually triggered
    inputs:
      customizedSdkUrlMasked:
         description: Download link
         required: true
      runner:
        description: runner
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-2019
          - macos-10.15

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: true

jobs:
  setup-parallel:
    runs-on: ${{ inputs.runner }}
    name: setup-parallel - ${{ inputs.runner }}_${{ matrix.suite }}
    strategy:
      fail-fast: true
      matrix:
        suite: [functional]
    steps:
      - uses: j-braley/run-aqa@v2.0.3
        name: Generate parallelList - ${{ matrix.suite }}
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrlMasked }}
          aqa-testsRepo: 'adoptium/aqa-tests:v0.9.6-release'
          build_list: ${{ matrix.suite }} # parallellist to generate
          target: ${{ matrix.suite }}
          run_parallel: true
          num_machines: 4

      - name: Archive parallelList - ${{ matrix.suite }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.suite }}-parallelList.mk
          path: ${{ github.workspace }}/aqa-tests/TKG/parallelList.mk

  run-aqa-parallel:
    runs-on: ${{ inputs.runner }}
    needs: setup-parallel
    name: Run AQAvit ${{ inputs.runner }} - _${{ matrix.suite }}.${{ matrix.test_list }}
    strategy:
      fail-fast: false
      matrix:
        test_list: ['testList_0', 'testList_1', 'testList_2', 'testList_3'] # numlist is hardcoded...for now
        suite: [functional]
    steps:
      - name: Download parallelList - ${{ matrix.suite }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.suite }}-parallelList.mk
          path: ./

      - name: Run AQA Parallel Test - ${{ matrix.suite }}_${{ matrix.test_list }}
        uses: j-braley/run-aqa@v2.0.3
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrlMasked }}
          aqa-testsRepo: 'adoptium/aqa-tests:v0.9.6-release'
          build_list: ${{ matrix.suite }}
          target : -f parallelList.mk ${{ matrix.test_list }}

      - uses: actions/upload-artifact@v2
        if: always() # Always run this step (even if the tests failed)
        with:
          name: test_output_${{ matrix.suite }}_${{ matrix.test_list }}
          path: ./**/output_*/*.tap
