name: Run AQAvit Paralleltest

on:
  workflow_dispatch: # Allows the job to be manually triggered
    inputs:
      customizedSdkUrl:
        description: SDK download URL
        required: true
      aqatest-repo:
        description: adoptium/aqa-tests repository
        required: true
        type: string
        default: 'adoptium/aqa-tests:v0.9.6-release'
      testImage:
        description: Native Libs URL
        required: true

env:  # Links to the JDK build under test and the native test libs
  USE_TESTENV_PROPERTIES: true

jobs:
  setup-parallel:
    runs-on: macos-12
    name: Run test
    steps:

      - name: Generate parallelList
        uses: adoptium/run-aqa@v2.0.1
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrl }}
          aqa-testsRepo: ${{ inputs.aqatest-repo }}
          build_list: ${{ matrix.suite }}
          target: ${{ matrix.suite }} # parallellist to generate
          run_parallel: true
          num_machines: 5

      - name: Archive parallelList - ${{ matrix.suite }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.suite }}-parallelList.mk
          path: ${{ github.workspace }}/aqa-tests/TKG/parallelList.mk

  run-aqa-parallel:
    runs-on: macos-12
    needs: setup-parallel
    name: Run AQAvit
    strategy:
      fail-fast: false
      matrix:
        test_list: ['testList_0', 'testList_1', 'testList_2', 'testList_3', 'testList_4'] # numlist is hardcoded...for now
    steps:
      - name: Download parallelList - ${{ matrix.suite }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.suite }}-parallelList.mk
          path: ./

      - name: Set TESTIMAGE_PATH
        working-directory: ${{ github.workspace }}
        if: ${{ inputs.system == 'linux' || inputs.system == 'macos' }}
        shell: bash
        run: |
          curl -o jdk-binaries.tar.gz ${{ inputs.testImage }}
          mkdir ./tmp && tar xvf jdk-binaries.tar.gz -C ./tmp
          file_name=$(ls ./tmp)
          jdk_path="${{ github.workspace }}/tmp/$file_name"
          echo "TESTIMAGE_PATH=$jdk_path" >> $GITHUB_ENV

      - name: Run AQA tests parallel (${{ inputs.system }}) - ${{ matrix.suite }}_${{ matrix.test_list }}
        uses: adoptium/run-aqa@v2.0.1
        if: ${{ inputs.system == 'windows' }}
        with:
          jdksource: 'customized'
          customizedSdkUrl: ${{ inputs.customizedSdkUrl }}
          aqa-testsRepo: ${{ inputs.aqatest-repo }}
          build_list: ${{ matrix.suite }}
          target : -f parallelList.mk ${{ matrix.test_list }}

      - uses: actions/upload-artifact@v2
        if: always() # Always run this step (even if the tests failed)
        with:
          name: test_output_${{ matrix.suite }}_${{ matrix.test_list }}
          path: ./**/output_*/*.tap
